version: "3.8"
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: eventdb
    ports:
      - "5432:5432"

  redis:
    image: redis
    ports:
      - "6379:6379"

  backend:
    build: .
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: "postgresql+asyncpg://postgres:password@db:5432/eventdb"
    ports:
      - "8000:8000"
